In [ ]:
cd drive/MyDrive/Colab\ Notebooks/chellage\ 45\ dataset

/content/drive/MyDrive/Colab Notebooks/chellage 45 dataset

In [ ]:
import pandas as pd
import numpy as np

# loading data

In [ ]:
df_test=pd.read_csv('test.csv')
df_train=pd.read_csv('train.csv')
df_sample_submission=pd.read_csv('sample_submission.csv')

In [ ]:
df_train.sample(5)

,CustomerID,Age,Gender,City,State,No_of_orders_placed,Sign_up_date,Last_order_placed_date,is_premium_member,Women’s_Clothing,Men’s_Clothing,Kid’s_Clothing,Home_&_Living,Beauty,Electronics,Preferred_Theme
13438,CusID_04248,34.0,Male,Chennai,British Columbia,10.0,2017-02-16,2021-08-06,0,0.666764,8.846703,4.596495,1.256687,2.176758,9.843287,Old_UI
2448,CusID_03858,NaN,Female,Los Angeles,California,7.0,2018-07-03,2020-03-06,0,8.524194,2.000000,1.000000,6.836461,7.051093,1.147368,Old_UI
13285,CusID_05664,35.0,Male,Vancouver,Maharashtra,NaN,2016-12-27,2020-07-24,1,8.259331,1.161756,5.327425,4.766404,4.796426,4.774098,Old_UI
1132,CusID_03784,35.0,Female,Vancouver,British Columbia,6.0,2018-01-09,2021-02-14,0,9.713005,4.162592,8.867387,7.652095,9.152052,1.619581,New_UI
13607,CusID_00434,28.0,Male,Munich,Ile-De-France,14.0,2016-01-19,2021-10-03,1,4.350927,3.390766,4.521194,3.787163,1.697400,6.472211,Old_UI

In [ ]:
df_train.shape

(15150, 16)

In [ ]:
df_train.columns

Index(['CustomerID', 'Age', 'Gender', 'City', 'State', 'No_of_orders_placed',
       'Sign_up_date', 'Last_order_placed_date', 'is_premium_member',
       'Women’s_Clothing', 'Men’s_Clothing', 'Kid’s_Clothing', 'Home_&_Living',
       'Beauty', 'Electronics', 'Preferred_Theme'],
      dtype='object')

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15150 entries, 0 to 15149
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              15150 non-null  object
 1   Age                     14147 non-null  float64
 2   Gender                  15150 non-null  object
 3   City                    15150 non-null  object
 4   State                   15150 non-null  object
 5   No_of_orders_placed     14377 non-null  float64
 6   Sign_up_date            15150 non-null  object
 7   Last_order_placed_date  15150 non-null  object
 8   is_premium_member       15150 non-null  int64
 9   Women’s_Clothing        15150 non-null  float64
 10  Men’s_Clothing          15150 non-null  float64
 11  Kid’s_Clothing          14215 non-null  float64
 12  Home_&_Living           14302 non-null  float64
 13  Beauty                  15150 non-null  float64
 14  Electronics             15150 non-null  float64
 15  Preferred_Theme         15150 non-null  object
dtypes: float64(8), int64(1), object(7)
memory usage: 1.8+ MB

above observation:-


*   this data set have some null values 
*   few coulumn convert dtype like [`Gender , City , State`] into int & also convert [`Sign_up_date , Last_order_placed_date`] datetime dtype

In [ ]:
df_train.describe()

,Age,No_of_orders_placed,is_premium_member,Women’s_Clothing,Men’s_Clothing,Kid’s_Clothing,Home_&_Living,Beauty,Electronics
count,14147.000000,14377.000000,15150.000000,15150.000000,15150.000000,14215.000000,14302.000000,15150.000000,15150.000000
mean,28.356613,8.200876,0.323828,1.848024,4.464372,4.573373,4.576805,4.069482,2.830962
std,7.563249,3.606418,0.467951,12.814344,2.979838,2.628990,2.380538,3.808290,13.056017
min,15.000000,0.000000,0.000000,-99.000000,-1.000000,-3.000000,-2.000000,-20.114294,-99.000000
25%,22.000000,5.000000,0.000000,1.301135,2.019508,2.602179,2.817589,1.135181,2.472861
50%,29.000000,8.000000,0.000000,3.305220,3.603376,4.826021,4.338659,2.914518,4.602270
75%,33.000000,10.000000,1.000000,6.656113,7.595931,6.482865,6.532475,7.634503,7.872561
max,50.000000,15.000000,1.000000,9.998061,9.999751,9.997132,9.993163,26.564845,9.999038

# Analysis

## how many different customer

In [ ]:
df_train['CustomerID'].nunique()

8150

## one user how many time view the UI update

In [ ]:
df_train['CustomerID'].value_counts()

CusID_03946    24
CusID_06118    23
CusID_09342    22
CusID_08240    21
CusID_01697    21
               ..
CusID_02985     1
CusID_08605     1
CusID_05668     1
CusID_00827     1
CusID_07843     1
Name: CustomerID, Length: 8150, dtype: int64

## unique values in different-different column

In [ ]:
for colu in df_train.columns:
    print(f' {colu} ---> {df_train[colu].nunique()}' )

 CustomerID ---> 8150
 Age ---> 36
 Gender ---> 3
 City ---> 23
 State ---> 21
 No_of_orders_placed ---> 16
 Sign_up_date ---> 1455
 Last_order_placed_date ---> 670
 is_premium_member ---> 2
 Women’s_Clothing ---> 13656
 Men’s_Clothing ---> 13959
 Kid’s_Clothing ---> 13463
 Home_&_Living ---> 13645
 Beauty ---> 13618
 Electronics ---> 13545
 Preferred_Theme ---> 2

In [ ]:
import seaborn as sns

## how many null values we have & which column have null values

In [ ]:
df_train.isnull().sum()

CustomerID                   0
Age                       1003
Gender                       0
City                         0
State                        0
No_of_orders_placed        773
Sign_up_date                 0
Last_order_placed_date       0
is_premium_member            0
Women’s_Clothing             0
Men’s_Clothing               0
Kid’s_Clothing             935
Home_&_Living              848
Beauty                       0
Electronics                  0
Preferred_Theme              0
dtype: int64

# DATA Preprocessing function 
take data and return X_data , y_data

In [ ]:
def preprocess_data(df_values,test_data=False):
    
    df_train=df_values.fillna(df_values.mean())  # fill na values to mean

    df_train['CustomerID']=df_train['CustomerID'].apply(lambda x:x.replace('CusID_','')).astype(np.int64)

    df_train=df_train.apply(lambda x:x.replace('?',df_train.median()))
    df_train=df_train.dropna(axis=0)

    # split date , month , year
    array_Sign_up_date=pd.to_datetime(df_train['Sign_up_date'],)
    df_train['Sign_up_day']=array_Sign_up_date.apply(lambda x:x.day)
    df_train['Sign_up_month']=array_Sign_up_date.apply(lambda x:x.month)
    df_train['Sign_up_year']=array_Sign_up_date.apply(lambda x:x.year)

    array_Last_order_placed_date=pd.to_datetime(df_train['Last_order_placed_date'],)
    df_train['Last_order_placed_day']=array_Last_order_placed_date.apply(lambda x:x.day)
    df_train['Last_order_placed_month']=array_Last_order_placed_date.apply(lambda x:x.month)
    df_train['Last_order_placed_year']=array_Last_order_placed_date.apply(lambda x:x.year)


    convert_col_int=['City','Gender','State']
    from sklearn.preprocessing import OneHotEncoder,LabelEncoder
    # enc = OneHotEncoder()
    enc=LabelEncoder()

    df_train['City']=enc.fit_transform(df_train['City'])
    df_train['Gender']=enc.fit_transform(df_train['Gender'])
    df_train['State']=enc.fit_transform(df_train['State'])


    if test_data:
        X_data=df_train.drop(['Sign_up_date','Last_order_placed_date',],axis=1)
        return X_data
    else:
        X_data=df_train.drop(['Sign_up_date','Last_order_placed_date','Preferred_Theme'],axis=1)
        y_data=df_train['Preferred_Theme']

        return X_data,y_data

In [ ]:
X_data ,y_data =preprocess_data(df_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  This is separate from the ipykernel package so we can avoid doing imports until

In [ ]:
# X_data=X_data.drop('Preferred_Theme',axis=1)
# y_data=df_train['Preferred_Theme']

In [ ]:
print(X_data.shape,y_data.shape)

(14555, 19) (14555,)

# spliting data set into train & test

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X_data, y_data, test_size=0.10, random_state=42)  # X,y variable name

# Modeling

## Desision tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
deci_clf = DecisionTreeClassifier(random_state=3,max_depth=100)

## Naive byas

In [ ]:
from sklearn.naive_bayes import GaussianNB

gauss = GaussianNB()

## randomForest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

ran_clf = RandomForestClassifier(max_depth=90, random_state=4,n_estimators=800) # increasing max_depth increasing training score

## SGDClassifier

In [ ]:
from sklearn.linear_model import SGDClassifier
sgd_clf = SGDClassifier(random_state=42,max_iter=1000)

## SVM

In [ ]:
from sklearn.svm import SVC

In [ ]:
sv_classifier=SVC(gamma='auto')
sv_classifier.fit(X_train,y_train)

SVC(gamma='auto')

# HELLO WORLD :)
so, we have three better model which have `low bias and low varience` , now i am **essamble model**

# Ensemble

In [ ]:
from sklearn.ensemble import VotingClassifier

model = VotingClassifier(estimators=[('sv', sv_classifier), ('sgd', sgd_clf),('ran',ran_clf),('dec',deci_clf)], voting='hard')
model.fit(X_train,y_train)

VotingClassifier(estimators=[('sv', SVC(gamma='auto')),
                             ('sgd', SGDClassifier(random_state=42)),
                             ('ran',
                              RandomForestClassifier(max_depth=90,
                                                     n_estimators=800,
                                                     random_state=4)),
                             ('dec',
                              DecisionTreeClassifier(max_depth=100,
                                                     random_state=3))])

In [ ]:
print(f'training score --> {model.score(X_train,y_train)}')
print(f'test score --> {model.score(X_test,y_test)}\n','-'*15)

training score --> 1.0
test score --> 0.5364010989010989
 ---------------

# cross validation score

In [ ]:
from sklearn.model_selection import cross_val_score

cross_val_score(model, X_train, y_train, cv=3, scoring="accuracy")

array([0.51774674, 0.67384333, 0.66353642])

# Now pridicting real data

In [ ]:
new_x_test=preprocess_data(df_test,True)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  This is separate from the ipykernel package so we can avoid doing imports until

In [ ]:
new_x_test

,CustomerID,Age,Gender,City,State,No_of_orders_placed,is_premium_member,Women’s_Clothing,Men’s_Clothing,Kid’s_Clothing,Home_&_Living,Beauty,Electronics,Sign_up_day,Sign_up_month,Sign_up_year,Last_order_placed_day,Last_order_placed_month,Last_order_placed_year
0,9654,20.0,0,20,2,5.0,0,4.000000,3.043023,6.231789,8.561328,9.893144,1.197478,27,11,2019,22,3,2020
1,9727,25.0,2,2,5,11.0,1,4.379066,5.819171,6.923614,4.529057,5.105539,4.608664,1,12,2016,22,8,2021
2,7391,31.0,0,14,20,1.0,1,7.946141,4.000000,9.939050,9.744879,8.874676,2.069313,31,10,2019,28,11,2020
3,8577,17.0,0,6,19,7.0,0,8.396490,3.636100,4.170301,8.412250,9.389648,3.103196,5,9,2019,20,3,2021
4,8122,39.0,1,12,11,8.0,0,2.443467,9.143171,6.307817,3.224570,1.892078,7.298316,17,7,2019,19,1,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1845,2254,33.0,1,1,1,4.0,0,2.000000,4.000000,8.689062,1.818221,1.373504,6.240590,25,1,2017,1,7,2020
1846,977,33.0,2,0,4,12.0,1,3.980759,3.156048,3.041988,4.222825,0.246231,5.355230,14,7,2017,9,10,2021
1847,148,36.0,1,3,15,8.0,0,4.616428,8.543362,3.659035,2.562233,2.443372,8.100531,11,7,2018,23,5,2021
1848,4876,30.0,0,16,16,10.0,0,8.203691,4.197555,1.000000,6.539577,8.820486,3.000000,8,8,2017,13,9,2020
1849,5091,34.0,0,19,12,8.0,0,7.601718,0.996902,3.000000,4.917128,8.229719,2.977800,17,10,2018,24,4,2021

In [ ]:
new_y_predict=model.predict(new_x_test)

In [ ]:
df_sample_submission.head(3)

    CustomerID Preferred_Theme
0  CusID_07992          New_UI
1  CusID_02410          Old_UI
2  CusID_05646          New_UI

In [ ]:
submission_file=pd.DataFrame()

In [ ]:
submission_file['CustomerID']=new_x_test["CustomerID"].apply(lambda x:f'CusID_{x}')

In [ ]:
submission_file['Preferred_Theme']=new_y_predict

In [ ]:
submission_file

      CustomerID Preferred_Theme
0     CusID_9654          New_UI
1     CusID_9727          New_UI
2     CusID_7391          New_UI
3     CusID_8577          New_UI
4     CusID_8122          New_UI
...          ...             ...
1845  CusID_2254          New_UI
1846   CusID_977          New_UI
1847   CusID_148          New_UI
1848  CusID_4876          New_UI
1849  CusID_5091          New_UI

[1785 rows x 2 columns]

In [ ]:
submission_file.to_csv('submission.csv')

In [ ]:
df_test.shape

(1850, 15)

In [ ]:
submission_file.shape

(1785, 2)